{
 "title": "LedgerX Distributed Monitors",
 "refresh": "5s",
 "panels": [
  {
   "title": "API HTTP Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_received_total[1m])",
     "legendFormat": "{{method}} {{controller}}"
    }
   ]
  },
  {
   "title": "Services Memory Footprint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_private_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "System CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}