global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'ledgerx-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ledgerx-api:5000']

  - job_name: 'ledgerx-workers'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ledgerx-workers:5001']
